---
- name: Include OS family vars
  include_vars:
    "{{ ansible_os_family }}.yaml"

# - name: Include OS distribution vars
#   include_vars:
#     "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yaml"

- name: Add InfluxData GPG key
  ansible.builtin.apt_key:
    url: "{{ telegraf__influxdata_key_url }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Add InfluxData Debian Repository
  ansible.builtin.apt_repository:
    repo: "{{ telegraf__influxdata_repo | lower }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install packages
  ansible.builtin.package:
    name: "{{ telegraf__packages }}"
    state: "present"
